spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    # 配置返回给前端的字段中,若有null的,跳过不返回,这里是全局配置,参考com.lwh.sell.dto.OrderDTO
    default-property-inclusion: non_null
  redis:
      host: 192.168.0.104
      port: 6379

server:
  context-path: /sell

wechat:
  # 公众账号,用于授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2

   # 开放平台,卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

  # 支付/商户号
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6

  # 证书,发起支付不需要证书,退款需要
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://liwanghong.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: CfDjBS7IQuzyDu8ZvMNlM3FJ2CFWoNzeibLYjk3XNNE

projectUrl:
  wechatMpAuthorize: http://liwanghong.natapp1.cc
  wechatOpenAuthorize: http://liwanghong.natapp1.cc
  sell: http://localhost:8080

#springboot集成logback有两种配置方式,一种是在application文件中配置,这种比较简单
#logging:
#  pattern:
#    # d是输出日期,msg是日志内容,n换行
#    console: "%d - %msg%n"
#  # path和file都可以配置日志输出的路径,配置一个就好,path默认是spring.log日志文件,file可以指定名称
#  path: D:/Others/
#  file: D:/Others/sell.log
#  level: debug